
spring:
  main:
    allow-circular-references: true

  datasource:
    url: jdbc:mariadb://localhost:3306/chat
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 2000

jwt:
  token:
    header: X-PRGRMS-AUTH
    issuer: chat
    client-secret: Rel3Bjce2MajBo09qgkNgYaTuzvJe8iwnBFhsDS5
    expiry-seconds: 0

logging.level:
  org.hibernate.SQL: debug